// css
import "@/styles/globals.css";
import "@rainbow-me/rainbowkit/styles.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { WagmiConfig } from "wagmi";

import { TRPCReactProvider } from "@/services/trpc/react";
import { chainData, wagmiConfig } from "@/services/wagmi";
import { RainbowKitProvider } from "@rainbow-me/rainbowkit";
import Navbar from "@/components/shared/Navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <WagmiConfig config={wagmiConfig}>
          <RainbowKitProvider chains={chainData}>
            <TRPCReactProvider cookies={cookies().toString()}>
              <Navbar />
              <main className="mt-8 px-6 md:px-0">{children}</main>
            </TRPCReactProvider>
          </RainbowKitProvider>
        </WagmiConfig>
      </body>
    </html>
  );
}
